# Application Configuration
#
# For business logic not tied to specific
# environment operating parameters.
#
# This configuration should be the same on
# local, development and production environments.
#
deasilworks:
  api:
    class_path: 'deasilworks\CMS\CEF\Manager'
    aliases:
        content: 'PageManager'
        acl: 'User\AclManager'

app:
  debug: true
  twig.path:
    - '%app_root%/../templates'
  twig.options:
    cache: '%app_root%/../var/cache/twig'