# Environment Parameters Configuration
#
# For specific environment based operating
# parameters.
#
# This configuration should only contain keys
# the differentiate operational configuration
# for local, development and production environments.
#
deasilworks:
  cef:
    keyspace: 'fl_cms'
    contact_points:
      - "127.0.0.1"

app:
  debug: false

  # only needed if app.debug is true
  monolog.logfile: '%app_root%/../var/logs/silex_dev.log'
  profiler.cache_dir: '%app_root%/../var/cache/profiler'