# Application Configuration
#
# For business logic not tied to specific
# environment operating parameters.
#
# This configuration should be the same on
# local, development and production environments.
#
deasilworks:
  api:
    routes:
      cms:
        class_path: 'deasilworks\CMS\CEF\Manager'
        aliases:
            content: 'PageDataManager'
      v1:
        class_path: 'MyProject\CEF\Manager'

app:
  twig.path:
    - '%app_root%/../templates'
  twig.options:
    cache: '%app_root%/../var/cache/twig'